//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataTable_edited.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PCEntities : DbContext
    {
        public PCEntities()
            : base("name=PCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<trn_kanban_loss_comment> trn_kanban_loss_comment { get; set; }
        public virtual DbSet<trn_kanban_loss_summary> trn_kanban_loss_summary { get; set; }
        public virtual DbSet<trn_kanban_machine_planned_loss> trn_kanban_machine_planned_loss { get; set; }
        public virtual DbSet<trn_kanban_machine_size_info> trn_kanban_machine_size_info { get; set; }
        public virtual DbSet<trn_kanban_productivity> trn_kanban_productivity { get; set; }
        public virtual DbSet<RawData> RawData { get; set; }
        public virtual DbSet<trn_shipping_AKO_Info> trn_shipping_AKO_Info { get; set; }
        public virtual DbSet<UsedRawData> UsedRawData { get; set; }
    }
}
