//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataTable_edited.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trn_shipping_AKO_Info
    {
        public int id { get; set; }
        public Nullable<System.DateTime> LOADING_DATE { get; set; }
        public string SHIPPING_INS_NO { get; set; }
        public string CONSIGNEE_NAME { get; set; }
        public string DOCK_NO { get; set; }
        public string STORE_YEAR_WEEK { get; set; }
        public string FACTORY_PART_NO6 { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string MARKET_NM { get; set; }
        public string TICKET_NO { get; set; }
        public string TIRE_BC { get; set; }
        public string VEHICLE_NUMBER { get; set; }
        public Nullable<System.DateTime> LOADING_TIME { get; set; }
        public string LOADING_WORKER { get; set; }
        public string EANCODE { get; set; }
        public Nullable<System.DateTime> PRODUCTDATE { get; set; }
        public Nullable<int> WEIGHT { get; set; }
        public Nullable<int> GAUGE { get; set; }
        public Nullable<byte> SEND_FLG { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_AT { get; set; }
    }
}
