//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataTable_edited.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsedRawData
    {
        public int id { get; set; }
        public string FactoryDate { get; set; }
        public string MaterialCode { get; set; }
        public string TotalWeight { get; set; }
    }
}
